### PR TITLE
Update repos.txt

### PR DESCRIPTION
**Pull request by ElectronicRave**
Hi, I created a new theme for pegasus based on the original retroid launcher for pocket 2 and 3, Please check it and if possible publish it, thank you

### CODE REVIEW

**Comment by mmatyas** [comment]
Hi, thanks for the submission! The site reads the theme information from the theme config file, so I would need it in an unzipped form on the repository. Take a look at the other themes or the [documentation](https://pegasus-frontend.org/docs/themes/overview/#themecfg) if you're unsure how it should look like.

**Comment by ElectronicRave** [comment]
Yes, I saw what the model would look like but I couldn't do it the same way, now with the documentation link I can find out more. thanks

**Comment by ElectronicRave** [comment]
> Olá, obrigado pelo envio! O site lê as informações do tema no arquivo de configuração do tema, então eu precisaria delas descompactadas no repositório. Você pode dar uma olhada nos outros temas ou na [ documentação ](https://pegasus-frontend.org/docs/themes/overview/#themecfg) se não tiver certeza de como deve ser a aparência.

I think I understand now how it all works. I was unable to send more than 100 files at a time. Now I sent it in parts and it worked. thanks

**Comment by ElectronicRave** [comment]
> Hi, thanks for the submission! The site reads the theme information from the theme config file, so I would need it in an unzipped form on the repository. You can take a look at the other themes or the [documentation](https://pegasus-frontend.org/docs/themes/overview/#themecfg) if you're unsure how it should look like.

I think I understand now how it all works. thanks...

**Comment by mmatyas** [comment]
Added, thanks! If you'd like to add screenshots or description to the theme, you can list these in the config file too. For example: https://github.com/Fr75s/library/blob/main/theme.cfg

**Comment by ElectronicRave** [comment]
It's always a pleasure to be part of projects like this. thank you for that...

**Pull request merged**
